name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Publishing
        run: |
                    ls
                    Publish-Module -Path .\PSKafkaTools.psd1 -NuGetApiKey ${{ secrets.PSGALLERY }} -Tag "Kafka" -LicenseUri "https://github.com/kenriortega/kafkatools-module-ps1/blob/main/LICENCE"
        shell: pwsh