name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Dotnet Publish
        run: dotnet publish -c Release --self-contained -o ./release/out/KafkaTools
      - name: Publishing
        run: |
                $parameters = @{
                    Path        = "./release/out/KafkaTools"
                }
                Publish-Module @parameters -NuGetApiKey ${{ secrets.PSGALLERY }} -Verbose
        shell: pwsh