name: PSGallery
on:
  release:
    types: [published]


env:
  VERSION_PSGALLERY: '1.0.2'
  VERSION_PSGALLERY_OSX: '1.0.2-osx'
  VERSION_PSGALLERY_WIN: '1.0.2-win'
  VERSION_PSGALLERY_LINUX: '1.0.2-linux'

jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Dotnet Publish
        run: dotnet publish --self-contained true -c Release -o .\release\out\KafkaTools
        run: |
                $parameters = @{
                    Path        = ".\release\out\KafkaTools"
                }
                Publish-Module @parameters -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh