name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Publishing
        run: |
                    $parameters = @{
                        Name        = "KafkaTools"
                        LicenseUri  = "https://github.com/kenriortega/kafkatools-module-ps1/blob/main/LICENCE"
                        Tag         = "Kafka","tools"
                        ReleaseNote = "Frist kafka tools module very simple."
                    }
                    Publish-Module @parameters -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh