name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Dotnet Publish OSX Compatible
        run: dotnet publish -c Release -r osx-x64 --self-contained
      - name: Publishing OSX
        run: |
                ((Get-Content -path bin\Release\netstandard2.0\osx-x64\publish\KafkaTools.psd1 -Raw) `
                    -replace "  ModuleVersion        = '1.0.1'", "  ModuleVersion        = '1.0.1-osx'" `
                ) | Set-Content -Path bin\Release\netstandard2.0\osx-x64\publish\KafkaTools.psd1
                $parameters = @{
                    Path        = "bin\Release\netstandard2.0\osx-x64\publish"
                }
                Publish-Module @parameters -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh

      - name: Dotnet Publish Win
        run: dotnet publish -c Release -r win-x64 --self-contained
      - name: Publishing win
        run: |
                ((Get-Content -path bin\Release\netstandard2.0\win-x64\publish\KafkaTools.psd1 -Raw) `
                    -replace "  ModuleVersion        = '1.0.1'", "  ModuleVersion        = '1.0.1-win'" `
                ) | Set-Content -Path bin\Release\netstandard2.0\win-x64\publish\KafkaTools.psd1
                $parameters = @{
                    Path        = "bin\Release\netstandard2.0\win-x64\publish"
                }
                Publish-Module @parameters -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh

      - name: Dotnet Publish Linux
        run: dotnet publish -c Release -r linux-x64 --self-contained
      - name: Publishing Linux
        run: |
                ((Get-Content -path bin\Release\netstandard2.0\linux-x64\publish\KafkaTools.psd1 -Raw) `
                    -replace "  ModuleVersion        = '1.0.1'", "  ModuleVersion        = '1.0.1-linux'" `
                ) | Set-Content -Path bin\Release\netstandard2.0\linux-x64\publish\KafkaTools.psd1        
                $parameters = @{
                    Path        = "bin\Release\netstandard2.0\linux-x64\publish"
                }
                Publish-Module @parameters -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh